---
hugo_env: &hugo_env
   BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/

kind: pipeline
name: hugo-website
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL
#push the build on s3 bucket
  - name: push-to-s3
    image: plugins/s3
    environment:
      <<: *hugo_env
    settings:
      bucket: deploy-landing
      endpoint: s3.amazonaws.com
      path: public/
      acl: public-read
      mime_type: auto
      cache_control: max-age=31536000, public