---
hugo_env: &hugo_env
  BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/

kind: pipeline
name: build
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

trigger:
  event:
    - push
  ref: 
    - master
---
kind: pipeline
name: build on master
steps:
  - name: hugo-build-stage
    image: peaceiris/hugo:v0.65.3-mod

    commands:
      - hugo --baseURL https://stage-landing-restau.s3.us-east-1.amazonaws.com/
    when:
      event: push
      branch: master

  - name: hugo-build-production
    image: peaceiris/hugo:v0.65.3-mod
    commands:
      - hugo --baseURL https://deploy-landing.s3.us-east-1.amazonaws.com/
    when:
      event: tag
      branch: master

  - name: create-zip-archive
    image: alpine:latest
    commands:
      - apk add --no-cache zip
      - |
        if [ "${DRONE_TAG}" != "" ]; then
          zip -r site-prod-${DRONE_TAG}.zip public/
        else
          zip -r site-pprd-${DRONE_COMMIT_SHA:0:8}.zip public/
        fi
    when:
      event: [push, tag]
      branch: master

  - name: push-to-staging
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
      S3_BUCKET: stage-landing-restau
      S3_REGION: us-east-1
    commands:
      - aws s3 sync public/ s3://stage-landing-restau/ --delete
    when:
      event: push
      branch: master

  - name: upload-zip-to-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 cp site-pprd-${DRONE_COMMIT_SHA:0:8}.zip s3://release-landing/stage/site-pprd-${DRONE_COMMIT_SHA:0:8}.zip
    when:
      event: push
      branch: master

  - name: upload-zip-to-s3-production
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
      S3_BUCKET: release-landing
      S3_REGION: us-east-1
    commands:
      - aws s3 cp site-prod-${DRONE_TAG}.zip s3://release-landing/production/site-prod-${DRONE_TAG}.zip
    when:
      event: tag
      branch: master

trigger:
  event:
    - [push, tag]
  branch:
    - master 

---
kind: pipeline
name: deploy
steps:
  - name: download-zip-from-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - apk add --no-cache zip
      - aws s3 cp s3://release-landing/production/site-prod-${DRONE_TAG}.zip .
      - unzip site-prod-${DRONE_TAG}.zip
      - rm -f site-prod-${DRONE_TAG}.zip
    when:
      event: promote
      target: production

  - name: upload-to-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync public/ s3://deploy-landing/ --delete
    when:
      event: promote
      target: production
    
  - name: download-zip-from-s3-stage
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - apk add --no-cache zip
      - aws s3 cp s3://release-landing/stage/site-pprd-${DRONE_COMMIT_SHA:0:8}.zip .
      - unzip site-pprd-${DRONE_COMMIT_SHA:0:8}.zip
      - rm -f site-pprd-${DRONE_COMMIT_SHA:0:8}.zip
    when:
      event: promote
      target: stage

  - name: upload-to-s3-stage
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync public/ s3://deploy-landing/ --delete
    when:
      event: promote
      target: stage
  
trigger:
  event:
    - promote
 
#testbe