---
hugo_env: &hugo_env
  BASE_URL: https://${DRONE_REPO_OWNER,,}.github.io/${DRONE_REPO_NAME}/

kind: pipeline
name: build
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

trigger:
  event:
    - push
---
kind: pipeline
name: build on maste
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      BASE_URL:
        from_secret: base_url_stage
    commands:
      - hugo --baseURL ${BASE_URL}

  - name: push-to-staging
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync public/ s3://stage-landing-restau/ --delete

  - name: zip-artifact
    image: alpine:3.20
    commands:
      - apk add --no-cache zip
      - cd public && zip -r ../site-${GIT_SHA}.zip .

  - name: upload-zip-to-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 cp site-${GIT_SHA}.zip s3://release-landing/stage/site-${GIT_SHA}.zip
trigger:
  event:
    - push
  ref:
    - master

---
kind: pipeline
name: release
steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      BASE_URL:
        from_secret: base_url
    commands:
      - hugo --baseURL ${BASE_URL}

  - name: zip-artifact
    image: alpine:3.20
    commands:
      - apk add --no-cache zip
      - cd public && zip -r ../site-${DRONE_TAG}.zip .

  - name: upload-zip-to-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 cp site-${DRONE_TAG}.zip s3://release-landing/production/site-${DRONE_TAG}.zip
trigger:
  event:
    - tag

---
kind: pipeline
name: deploy
steps:
  - name: download-zip-from-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 cp s3://deploy-landing/releases/site-${DRONE_TAG}.zip .
      - unzip site-${DRONE_TAG}.zip
      - rm -f site-${DRONE_TAG}.zipr

  - name: upload-to-s3
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      AWS_SESSION_TOKEN:
        from_secret: aws_session_token
      AWS_DEFAULT_REGION: us-east-1
    commands:
      - aws s3 sync public/ s3://deploy-landing/ --delete
trigger:
  event:
    - promote
  target:
    - production
#testbe